from .config import CONFIG, SAMPLE_SUBMISSION_TSV, IA_TSV, TESTSUPERSET_TAXON_LIST_TSV
from .config import TRAIN_TERMS_TSV, TRAIN_TAXONOMY_TSV, TESTSUPERSET_FASTA
from .config import TRAIN_SEQUENCES_FASTA, GO_BASIC_OBO, OUTPUT_TSV

__all__ = [
    'CONFIG',
    'SAMPLE_SUBMISSION_TSV',
    'IA_TSV',
    'TESTSUPERSET_TAXON_LIST_TSV',
    'TRAIN_TERMS_TSV',
    'TRAIN_TAXONOMY_TSV',
    'TESTSUPERSET_FASTA',
    'TRAIN_SEQUENCES_FASTA',
    'GO_BASIC_OBO',
    'OUTPUT_TSV'
]
